server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easytransfert
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  devtools:
    restart:
      enabled=true: